### ISSUE TITLE
MVC Design Structure

### ISSUE THREAD

**Issue by qk8333** [qk8333/CS4311_03#4]
The assignment states we are supposed to use the model-view-controller (MVC) pattern to implement our code. If anyone can look over it and make sure I'm following the pattern and give a second opinion, that would be great. The assignment also states that it is intended to give us "more experience with the Observer pattern" which I didn't directly use anywhere in my code (this assumes that Observable and Observer objects from the java library MUST be used). Other than that the program functions just as intended (however, there are no unittests and I'm not sure how well the code will function if under duress (i.e. toggling a button really fast)).

**Comment by qk8333** [comment]
Please submit your observations in a comment.

**Comment by conklinbrendan** [comment]
The software looks like it follows MVC to the best of my knowledge. I did find some weird behavior when toggling buttons in the grid quickly in specific and uncommon circumstances but these don't seem to be issues as far I am concerned.
